#include "frontend/parser_driver.hpp"

#include <memory>
#include <string>

#include "lexer.lex.hpp"  // generated by Flex; declares yy_size_t, yy_scan_bytes, etc.

#include "ast/ast.hpp"
#include "support/diagnostic.hpp"

extern int yyparse(void);

namespace toycc::frontend {

extern std::unique_ptr<ast::CompUnit> g_parseResult;

std::unique_ptr<ast::CompUnit> parseSource(const std::string &source) {
  g_parseResult.reset();
  YY_BUFFER_STATE buffer = yy_scan_bytes(source.data(), source.size());
  const int result = yyparse();
  yy_delete_buffer(buffer);
  yylex_destroy();
  if (result != 0 || !g_parseResult) fatal("failed to parse source");
  return std::move(g_parseResult);
}

}  // namespace toycc::frontend
